name: github pages

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get -qq update
          sudo apt-get install -y make pdftk xfonts-base xfonts-75dpi \
            chromium-browser fonts-noto language-pack-zh-hant \
            fonts-wqy-microhei ttf-wqy-microhei fonts-wqy-zenhei \
            ttf-wqy-zenhei fonts-noto-cjk wkhtmltopdf pandoc make pdftk || true
          fc-cache -f -v || true

      - name: Run build
        run: |
          make html pdf || true

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          cname: resume.divazone.tw
